/**
 * Generate the three per-node glaseld.toml files for the live BGW mesh.
 *
 * node-1 = dealer + submitter (holds the real cluster X25519 key + BLS group
 * secret + the funded submitter key). node-2/node-3 are compute-only peers: zero
 * cluster key (they never decrypt), dummy BLS secret (they never submit). All
 * three share the same Noise roster (public IP:port + static pubkey, in party
 * order). Writes /tmp/glaseld-node{1,2,3}.toml.
 *
 * Run: cd sdk && bun run scripts/gen-mpc-configs.ts <currentBlock>
 */
import { keccak256, toHex } from "viem";
import { readFileSync, writeFileSync } from "node:fs";

const ROOT = new URL("../..", import.meta.url).pathname;
const state = JSON.parse(readFileSync(`${ROOT}/contracts/golive-state.json`, "utf8"));
// Mesh roster + Noise identity keys (gitignored — the privs are mesh secrets).
// Generate keys with: cargo run -p glasel-mpc --example noise_keygen -- 3
const mesh = JSON.parse(readFileSync(`${ROOT}/contracts/mpc-mesh.json`, "utf8"));
const MESH_PORT: number = mesh.port;
const NODES: { ip: string; noisePriv: string; noisePub: string }[] = mesh.nodes;
// Deterministic node operator keys (same identities as the on-chain cluster).
const nodeKeys = [1, 2, 3].map((i) => keccak256(toHex(`glasel-testnet-node-${i}`)));

const startBlock = process.argv[2] ?? "0";
const ZERO_KEY = "0x" + "00".repeat(32);
const DUMMY_BLS = "01"; // valid hex; unused on non-submitters (they never sign)
// The real group secret comes from the gitignored golive-state (never hardcoded).
// Experimental BGW-mesh tooling — the live network runs a single daemon.
const BLS_SECRET: string = state.blsSecret;
if (!BLS_SECRET) throw new Error("golive-state.json has no blsSecret — run golive-wire first (it generates + persists a random one)");

const contracts = `[contracts]
coordinator = "0x1FbB367715D26F752357dc7ee60b957CB40d8452"
cluster_manager = "0x875975030Ea94dDbEacfb5fcb9dAeaD4dC70A523"
computation_registry = "0x359e6fd81BD1EAE7F4ae7a7Fdc29b1986f679F72"`;

const roster = NODES.map(
  (n) => `[[mpc.parties]]\naddr = "${n.ip}:${MESH_PORT}"\npubkey = "${n.noisePub}"`,
).join("\n\n");

for (let i = 0; i < 3; i++) {
  const partyId = i + 1;
  const isDealer = partyId === 1;
  const toml = `# glaseld.toml — node-${partyId} of the live BGW mesh (generated by gen-mpc-configs.ts).
# party ${partyId}${isDealer ? " = dealer + submitter" : " = compute-only peer"}.
rpc_url = "https://sepolia.base.org"
poll_interval_ms = 4000
start_block = ${startBlock}
run_once = false
metrics_addr = "0.0.0.0:9090"

${contracts}

[cluster]
# Only the dealer holds the real cluster key (it decrypts inputs before sharing);
# peers get a zero key so they genuinely cannot decrypt. The BLS group secret is
# real on the submitter (it signs) and a dummy on peers (they never submit).
x25519_private_key = "${isDealer ? state.clusterPriv : ZERO_KEY}"
bls_group_secret = "${isDealer ? BLS_SECRET : DUMMY_BLS}"

[engine]

[signers]
keys = ["${nodeKeys[i]}"]

[mpc]
party_id = ${partyId}
dealer_id = 1
threshold = 1
identity_private_key = "${NODES[i]!.noisePriv}"
submitter = ${isDealer}

${roster}
`;
  const path = `/tmp/glaseld-node${partyId}.toml`;
  writeFileSync(path, toml);
  console.log(`wrote ${path}  (party ${partyId}${isDealer ? ", dealer+submitter" : ""})`);
}
