//! Compile the Glasel circuit IR to an MP-SPDZ high-level (`.mpc`) program and
//! run it under **MASCOT** — malicious security against a dishonest majority
//! (authenticated Beaver triples + MAC-checked opens), the production-grade
//! replacement for the semi-honest BGW backend in `glasel-mpc`.
//!
//! The codegen ([`compile_to_mpspdz`]) is pure and unit-tested. The runner
//! ([`run_mascot`]) shells out to a built MP-SPDZ (see `node/scripts/setup-mpspdz.sh`);
//! it is exercised by a gated integration test that checks the malicious-secure
//! output matches the in-process [`crate::evaluate`].
use crate::ir::{Circuit, Gate};
use glasel_crypto::field;
use num_bigint::BigUint;
use std::path::Path;
use std::process::Command;
use std::sync::Mutex;

/// Serializes MASCOT runs that share one MP-SPDZ tree. The program source,
/// per-party `Player-Data/Input-P<j>-0` files, and compiled bytecode all live at
/// fixed paths under `mpspdz_dir`, so two concurrent runs would clobber each
/// other's inputs and produce a wrong (yet still MAC-valid) result. A daemon
/// processing computations concurrently, or cargo running these e2e tests on
/// parallel threads, both hit this — so prepare+run is made atomic per process.
/// (Cross-process isolation is by giving each node its own `mpspdz_dir`.)
static MPSPDZ_RUN_LOCK: Mutex<()> = Mutex::new(());

/// Emit an MP-SPDZ program for `circuit`. `input_owner[i]` is the 0-indexed party
/// that provides input wire `i` (read via `sint.get_input_from`). Each output wire
/// is revealed and printed as a parseable `out <decimal>` line, in order.
pub fn compile_to_mpspdz(circuit: &Circuit, input_owner: &[usize]) -> String {
    assert_eq!(
        input_owner.len(),
        circuit.input_count as usize,
        "one owner per input wire"
    );
    let mut s = String::new();
    s.push_str("# auto-generated by glasel-circuit::mpspdz — MASCOT (malicious-secure) program\n");
    s.push_str("# wires 0..input_count are inputs; gate g produces wire input_count+g.\n");

    for i in 0..circuit.input_count as usize {
        s.push_str(&format!("w{i} = sint.get_input_from({})\n", input_owner[i]));
    }
    for (g, gate) in circuit.gates.iter().enumerate() {
        let out = circuit.input_count as usize + g;
        let expr = match gate {
            Gate::Add { a, b } => format!("w{a} + w{b}"),
            Gate::Mul { a, b } => format!("w{a} * w{b}"),
            Gate::AddConst { a, c } => format!("w{a} + {c}"),
            Gate::MulConst { a, c } => format!("w{a} * {c}"),
            Gate::Const { c } => format!("sint({c})"),
            // MP-SPDZ sint comparisons return a secret 0/1; if_else(x,y) = self?x:y.
            Gate::Lt { a, b } => format!("(w{a} < w{b})"),
            Gate::Eq { a, b } => format!("(w{a} == w{b})"),
            Gate::Select { cond, a, b } => format!("w{cond}.if_else(w{a}, w{b})"),
        };
        s.push_str(&format!("w{out} = {expr}\n"));
    }
    for w in &circuit.outputs {
        s.push_str(&format!("print_ln('out %s', w{w}.reveal())\n"));
    }
    s
}

/// Per-party private inputs for a [`run_mascot`] call: `inputs[i]` is the cleartext
/// value of input wire `i`, provided by party `input_owner[i]`.
pub struct MascotRun<'a> {
    pub mpspdz_dir: &'a Path,
    pub program: &'a str,
    pub circuit: &'a Circuit,
    pub inputs: &'a [BigUint],
    pub input_owner: &'a [usize],
    /// Number of parties (each provides inputs / participates). MASCOT default = 2.
    pub parties: usize,
}

/// Parse the revealed outputs from a party's stdout (`out <decimal>` lines).
fn parse_outputs(stdout: &str) -> Vec<BigUint> {
    stdout
        .lines()
        .filter_map(|l| l.strip_prefix("out "))
        .filter_map(|v| BigUint::parse_bytes(v.trim().as_bytes(), 10))
        .collect()
}

/// Write the program + per-party input files and compile to bytecode over our
/// field prime (2^255-19). Shared by the local and distributed runners.
fn prepare(run: &MascotRun) -> Result<(), String> {
    let dir = run.mpspdz_dir;
    if !dir.join("mascot-party.x").exists() {
        return Err(format!(
            "mascot-party.x not found in {} (run node/scripts/setup-mpspdz.sh)",
            dir.display()
        ));
    }
    assert_eq!(
        run.inputs.len(),
        run.circuit.input_count as usize,
        "inputs must match input_count"
    );

    let src = compile_to_mpspdz(run.circuit, run.input_owner);
    std::fs::write(
        dir.join("Programs/Source")
            .join(format!("{}.mpc", run.program)),
        src,
    )
    .map_err(|e| format!("write program: {e}"))?;

    for j in 0..run.parties {
        let vals: Vec<String> = (0..run.inputs.len())
            .filter(|&i| run.input_owner[i] == j)
            .map(|i| run.inputs[i].to_str_radix(10))
            .collect();
        std::fs::write(
            dir.join(format!("Player-Data/Input-P{j}-0")),
            vals.join(" "),
        )
        .map_err(|e| format!("write inputs P{j}: {e}"))?;
    }

    let prime = field::p().to_str_radix(10);
    let compile = Command::new("python3")
        .current_dir(dir)
        .args(["./compile.py", "-P", &prime, run.program])
        .output()
        .map_err(|e| format!("spawn compile.py: {e}"))?;
    if !compile.status.success() {
        return Err(format!(
            "compile.py failed:\n{}",
            String::from_utf8_lossy(&compile.stderr)
        ));
    }
    Ok(())
}

/// Compile + run the circuit under MASCOT with all parties **co-launched on one
/// host** (`Scripts/mascot.sh`). Convenient for local use/tests; see
/// [`run_mascot_distributed`] for one-party-per-node.
pub fn run_mascot(run: &MascotRun) -> Result<Vec<BigUint>, String> {
    // Hold the lock across prepare+run so a concurrent run can't overwrite this
    // run's input files between compilation and execution (poisoned-lock safe).
    let _guard = MPSPDZ_RUN_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    prepare(run)?;
    let out = Command::new("Scripts/mascot.sh")
        .current_dir(run.mpspdz_dir)
        .arg(run.program)
        .output()
        .map_err(|e| format!("spawn mascot.sh: {e}"))?;
    let stdout = String::from_utf8_lossy(&out.stdout);
    if !out.status.success() {
        return Err(format!(
            "mascot run failed:\n{stdout}\n{}",
            String::from_utf8_lossy(&out.stderr)
        ));
    }
    let outs = parse_outputs(&stdout);
    if outs.len() != run.circuit.outputs.len() {
        return Err(format!(
            "expected {} outputs, parsed {}:\n{stdout}",
            run.circuit.outputs.len(),
            outs.len()
        ));
    }
    Ok(outs)
}

/// Launch **one** MASCOT party (this node) for an already-prepared program and
/// return its revealed outputs. This is the per-node primitive for a distributed
/// deployment: the program bytecode, TLS certs, and this party's
/// `Player-Data/Input-P<party_id>-0` must already be present. `host` is party 0's
/// address (every party dials it); all parties share `port`. Invocation matches
/// `mascot.sh`: `mascot-party.x <party_id> <program> -N <n> -h <host> -pn <port>`.
pub fn run_mascot_party(
    mpspdz_dir: &Path,
    program: &str,
    party_id: usize,
    parties: usize,
    host: &str,
    port: u16,
) -> Result<Vec<BigUint>, String> {
    let out = Command::new("./mascot-party.x")
        .current_dir(mpspdz_dir)
        .args([
            &party_id.to_string(),
            program,
            "-N",
            &parties.to_string(),
            "-h",
            host,
            "-pn",
            &port.to_string(),
        ])
        .output()
        .map_err(|e| format!("spawn mascot-party.x: {e}"))?;
    let stdout = String::from_utf8_lossy(&out.stdout);
    if !out.status.success() {
        return Err(format!(
            "party {party_id} failed:\n{stdout}\n{}",
            String::from_utf8_lossy(&out.stderr)
        ));
    }
    Ok(parse_outputs(&stdout))
}

/// Run the circuit across `parties` **independent** party processes — the
/// distributed model (one process per GlaselOS node). Here they run on `host`
/// (localhost for tests; real per-node IPs in production), each launched
/// separately and connected over the network. Returns party 0's outputs after
/// checking every party agrees. (Compiles the program + lays down inputs once on
/// the shared dir; a real multi-host deploy distributes the bytecode + certs.)
pub fn run_mascot_distributed(
    run: &MascotRun,
    host: &str,
    port: u16,
) -> Result<Vec<BigUint>, String> {
    let _guard = MPSPDZ_RUN_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    prepare(run)?;
    let (dir, program, n) = (run.mpspdz_dir, run.program, run.parties);
    let outputs: Vec<Result<Vec<BigUint>, String>> = std::thread::scope(|s| {
        let handles: Vec<_> = (0..n)
            .map(|i| s.spawn(move || run_mascot_party(dir, program, i, n, host, port)))
            .collect();
        handles
            .into_iter()
            .map(|h| {
                h.join()
                    .unwrap_or_else(|_| Err("party thread panicked".into()))
            })
            .collect()
    });

    // Every party must complete (run_mascot_party errors on a non-zero exit), but
    // MP-SPDZ's `print_ln` emits only on party 0 — so party 0 carries the result.
    let mut per_party = Vec::with_capacity(n);
    for (i, r) in outputs.into_iter().enumerate() {
        per_party.push(r.map_err(|e| format!("party {i}: {e}"))?);
    }
    let result = per_party.into_iter().next().unwrap_or_default();
    if result.len() != run.circuit.outputs.len() {
        return Err(format!(
            "expected {} outputs from party 0, got {}",
            run.circuit.outputs.len(),
            result.len()
        ));
    }
    Ok(result)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{Circuit, Gate};

    #[test]
    fn codegen_emits_expected_program() {
        // order_notional: w0 (party 0) * w1 (party 1)
        let c = Circuit {
            input_count: 2,
            gates: vec![Gate::Mul { a: 0, b: 1 }],
            outputs: vec![2],
        };
        let src = compile_to_mpspdz(&c, &[0, 1]);
        assert!(
            src.contains("w0 = sint.get_input_from(0)"),
            "input 0 from party 0"
        );
        assert!(
            src.contains("w1 = sint.get_input_from(1)"),
            "input 1 from party 1"
        );
        assert!(src.contains("w2 = w0 * w1"), "mul gate → wire 2");
        assert!(
            src.contains("print_ln('out %s', w2.reveal())"),
            "reveal output wire 2"
        );
    }

    #[test]
    fn codegen_handles_all_gate_kinds() {
        // w2=w0+w1, w3=w2*w0, w4=w3+5, w5=w4*3, w6=const 9 ; outputs [w5, w6]
        let c = Circuit {
            input_count: 2,
            gates: vec![
                Gate::Add { a: 0, b: 1 },
                Gate::Mul { a: 2, b: 0 },
                Gate::AddConst {
                    a: 3,
                    c: BigUint::from(5u32),
                },
                Gate::MulConst {
                    a: 4,
                    c: BigUint::from(3u32),
                },
                Gate::Const {
                    c: BigUint::from(9u32),
                },
            ],
            outputs: vec![5, 6],
        };
        let src = compile_to_mpspdz(&c, &[0, 1]);
        for needle in [
            "w2 = w0 + w1",
            "w3 = w2 * w0",
            "w4 = w3 + 5",
            "w5 = w4 * 3",
            "w6 = sint(9)",
        ] {
            assert!(src.contains(needle), "missing: {needle}");
        }
        assert_eq!(
            src.matches("print_ln('out %s'").count(),
            2,
            "two outputs revealed"
        );
    }
}
