//! Cross-language interop: asserts the Rust crypto stack reproduces vectors
//! generated by the TypeScript SDK (sdk/scripts/gen-vectors.ts).
use glasel_crypto::{
    crypto::{self, shared_secret_fe},
    field, rescue,
};
use num_bigint::BigUint;
use serde::Deserialize;

#[derive(Deserialize)]
struct Vectors {
    permutation: Perm,
    #[serde(rename = "rescueHash")]
    rescue_hash: Hash,
    ctr: Ctr,
    ecdh: Ecdh,
    sealed: Sealed,
}
#[derive(Deserialize)]
struct Perm {
    input: Vec<String>,
    output: Vec<String>,
}
#[derive(Deserialize)]
struct Hash {
    input: Vec<String>,
    #[serde(rename = "outLen")]
    out_len: usize,
    output: Vec<String>,
}
#[derive(Deserialize)]
struct Ctr {
    secret: String,
    #[serde(rename = "nonceFe")]
    nonce_fe: String,
    plaintext: Vec<String>,
    ciphertext: Vec<String>,
}
#[derive(Deserialize)]
struct Ecdh {
    #[serde(rename = "privateKey")]
    private_key: String,
    #[serde(rename = "peerPublicKey")]
    peer_public_key: String,
    #[serde(rename = "sharedFe")]
    shared_fe: String,
}
#[derive(Deserialize)]
struct Sealed {
    #[serde(rename = "recipientPrivateKey")]
    recipient_private_key: String,
    #[serde(rename = "payloadHex")]
    payload_hex: String,
    #[serde(rename = "expectedPlaintext")]
    expected_plaintext: Vec<String>,
}

fn bn(s: &str) -> BigUint {
    s.parse().unwrap()
}
fn bnv(v: &[String]) -> Vec<BigUint> {
    v.iter().map(|s| bn(s)).collect()
}
fn key32(hex_str: &str) -> [u8; 32] {
    let b = hex::decode(hex_str.trim_start_matches("0x")).unwrap();
    let mut out = [0u8; 32];
    out.copy_from_slice(&b);
    out
}

fn load() -> Vectors {
    let raw = include_str!("vectors.json");
    serde_json::from_str(raw).expect("vectors.json")
}

#[test]
fn permutation_matches_ts() {
    let v = load();
    let out = rescue::permute(&bnv(&v.permutation.input));
    assert_eq!(out, bnv(&v.permutation.output));
}

#[test]
fn rescue_hash_matches_ts() {
    let v = load();
    let out = rescue::rescue_hash(&bnv(&v.rescue_hash.input), v.rescue_hash.out_len, 7, 5);
    assert_eq!(out, bnv(&v.rescue_hash.output));
}

#[test]
fn ctr_cipher_matches_ts() {
    let v = load();
    let key = rescue::derive_key(&bn(&v.ctr.secret));
    let nonce_fe = bn(&v.ctr.nonce_fe);
    let ct = rescue::ctr_encrypt(&bnv(&v.ctr.plaintext), &key, &nonce_fe);
    assert_eq!(ct, bnv(&v.ctr.ciphertext));
    // and decryption round-trips
    let pt = rescue::ctr_decrypt(&ct, &key, &nonce_fe);
    assert_eq!(pt, bnv(&v.ctr.plaintext));
}

#[test]
fn ecdh_matches_ts() {
    let v = load();
    let shared = shared_secret_fe(&key32(&v.ecdh.private_key), &key32(&v.ecdh.peer_public_key));
    assert_eq!(shared, bn(&v.ecdh.shared_fe));
}

#[test]
fn decrypts_ts_sealed_payload() {
    let v = load();
    let bytes = hex::decode(v.sealed.payload_hex.trim_start_matches("0x")).unwrap();
    let payload = crypto::deserialize_payload(&bytes).unwrap();
    let recovered = crypto::decrypt(&payload, &key32(&v.sealed.recipient_private_key));
    assert_eq!(recovered, bnv(&v.sealed.expected_plaintext));
}

#[test]
fn field_serialization_roundtrip() {
    let x = bn("123456789012345678901234567890");
    assert_eq!(field::fe_from_bytes_be(&field::fe_to_bytes_be(&x)), x);
}
